language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.6
addons:
  postgresql: '9.3'
services:
  - mongodb
before_script:
  - psql -c 'CREATE ROLE useless LOGIN;' -U postgres
  - psql -c 'CREATE DATABASE useless_books_test OWNER useless;' -U postgres
  - psql -c 'CREATE DATABASE useless_budget_test OWNER useless;' -U postgres
  - psql -c 'CREATE DATABASE useless_haiku_test OWNER useless;' -U postgres
  - psql -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;' -U postgres useless_books_test
