language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.6
addons:
  postgresql: '9.3'
services:
  - mongodb
before_script:
  - psql -c 'CREATE ROLE useless LOGIN;' -U postgres
  - psql -c 'CREATE DATABASE useless_books_test OWNER useless;' -U postgres
  - psql -c 'CREATE DATABASE useless_budget_test OWNER useless;' -U postgres
  - psql -c 'CREATE DATABASE useless_haiku_test OWNER useless;' -U postgres
  - psql -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;' -U postgres useless_books_test
  - git clone git@github.com:EVENFinancial/schema-evolution-manager.git
  - pushd schema-evolution-manager
  - git checkout 0.9.21
  - ruby ./configure.rb --prefix ~/sem
  - ./install.rb
  - popd
  - PATH=~/sem/bin:$PATH ./modules/apis/haiku/schema/test.rb
