language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.6
addons:
  postgresql: '9.3'
services:
  - mongodb
before_script:
  - psql -c 'CREATE ROLE useless LOGIN;' -U postgres
  - psql -c 'CREATE DATABASE useless_books_test OWNER even;' -U postgres
